services:
- postgresql
before_script:
 - psql -c 'create database teste;' -U postgres
# - psql -U postgres -d demoiselledb -f scripts/database/create_tables.sql
# - psql -U postgres -d demoiselledb -f scripts/database/db_inserts_script.sql
# - cd src/Demoiselle
# - ls
#language: java
#jdk:
#  - oraclejdk8
#script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
